### ISSUE TITLE
TypeError: String required

### ISSUE THREAD

**Issue by demalexx** [SublimeText/UnitTesting#117]
I installed UnitTesting package, selected "UnitTesting" in Commands palette and got this error in console:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1007, in run_
    return self.run()
  File "C:\Users\demalexx\AppData\Roaming\Sublime Text 3\Packages\UnitTesting\unittesting\test_package.py", line 18, in run
    self.prompt_package(lambda x: self.run(x, **kargs))
  File "C:\Users\demalexx\AppData\Roaming\Sublime Text 3\Packages\UnitTesting\unittesting\mixin.py", line 67, in prompt_package
    'Package:', package, callback, None, None)
  File "C:\Program Files\Sublime Text 3\sublime.py", line 434, in show_input_panel
    self.window_id, caption, initial_text, on_done, on_change, on_cancel))
TypeError: String required
```
Obviously I can't type package name and run tests. Tried in Windows 10 and MacOS.

**Comment by randy3k** [comment]
The `UnitTesting` command should be removed at some point. Please use the command which detects the package name directly.
