### ISSUE TITLE
Cannot run UnitTesting tests

### ISSUE THREAD

**Issue by rwols** [SublimeText/UnitTesting#168]
I forked this package to make some modifications, but I cannot seem to run the tests from this package. When I select "UnitTesting: Test Current Package" from the command palette, this happens:

```
reloading python 3.3 plugin AutomaticPackageReloader33.package_reloader
reloading python 3.3 plugin UnitTesting33.ut
[Package Reloader] begin ======================================================
Traceback (most recent call last):
  File "/home/raoul/.config/sublime-text-3/Packages/UnitTesting/unittesting/current.py", line 19, in <lambda>
    lambda: super(UnitTestingCurrentPackageCommand, self).run(**kwargs))
  File "/home/raoul/.config/sublime-text-3/Packages/UnitTesting/unittesting/package.py", line 45, in run
    self.unit_testing(stream, package, settings)
  File "/home/raoul/.config/sublime-text-3/Packages/UnitTesting/unittesting/current.py", line 24, in unit_testing
    self.reload_package(
  File "/home/raoul/.config/sublime-text-3/Packages/UnitTesting/unittesting/mixin.py", line 129, in reload_package
    reload_package(package, dummy=dummy, verbose=True)
  File "/home/raoul/.config/sublime-text-3/Packages/UnitTesting/unittesting/utils/reloader.py", line 94, in reload_package
    modules = get_package_modules(pkg_name)
  File "/home/raoul/.config/sublime-text-3/Packages/UnitTesting/unittesting/utils/reloader.py", line 73, in get_package_modules
    return {
  File "/home/raoul/.config/sublime-text-3/Packages/UnitTesting/unittesting/utils/reloader.py", line 76, in <dictcomp>
    if module_in_package(module)
  File "/home/raoul/.config/sublime-text-3/Packages/UnitTesting/unittesting/utils/reloader.py", line 69, in module_in_package
    in_installed_path(file) or any(map(in_installed_path, paths)) or
  File "/home/raoul/.config/sublime-text-3/Packages/UnitTesting/unittesting/utils/reloader.py", line 48, in path_contains
    return a == b or b.startswith(a + os.sep)
AttributeError: 'NoneType' object has no attribute 'startswith'
```

AutomaticPackageReloader seems to be breaking?

**Comment by randy3k** [comment]
Oh, it’s UnitTesting to blame. It only affects ST4.

**Comment by randy3k** [comment]
e7d02b3 should fix it.

It was due to a regression recently
