### ISSUE TITLE
AssertionError: final test result must not be None

### ISSUE THREAD

**Issue by gerardroche** [SublimeText/UnitTesting#83]
Test runs fail with:

```
Traceback (most recent call last):
  File "/home/travis/.config/sublime-text-3/Packages/UnitTesting/sbin/run_tests.py", line 207, in <module>
    main(default_schedule_info)
  File "/home/travis/.config/sublime-text-3/Packages/UnitTesting/sbin/run_tests.py", line 175, in main
    if not read_output(output_file):
  File "/home/travis/.config/sublime-text-3/Packages/UnitTesting/sbin/run_tests.py", line 132, in read_output
    assert success is not None, 'final test result must not be None'
AssertionError: final test result must not be None
```

Raw log: https://api.travis-ci.org/v3/job/343359191/log.txt
Travis CI: https://travis-ci.org/gerardroche/sublime-monokai-free/builds/343359190

Affects the latest master branch: 12db8e37c07fac9e71406a0349c85a6baa124bbc

**Comment by randy3k** [comment]
@guillermooo it seems it is related to the recent refactoring of `run_trst.py`

**Comment by randy3k** [comment]
@gerardroche could you try if the current master have fixed it?
